multi_puma_node:
  ros__parameters:
    canbus_dev: 'can0'
    joint_names: ['front_left_wheel_joint', 'front_right_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint']
    joint_can_ids: [2, 3, 4, 5]
    joint_directions_: [1, -1, 1, -1]
    gear_ratio: 24.0
    encoder_cpr: 10
    gain:
      p: 0.025
      i: 0.005
      d: 0.0
